# GolangCI-Lint configuration for Sentinel Hub API
# This helps IDEs understand the codebase structure

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
    - .git

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  govet:
    check-shadowing: true
  unused:
    check-exported: false

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosimple
        - staticcheck
